site_name: Golem Wiki
site_description: Golem Network Wiki - manual for running Golem node on your machine
site_author: Golem-Team

theme:
  # name: 'readthedocs'
  # name: 'material'
  name: 'cinder'

extra_css:
  - "css/golem_style.css"

# repo_name: github
repo_url: https://github.com/golemfactory/golem/
edit_uri: ""

markdown_extensions:
    - fenced_code
    - codehilite
    - mdx_math
    - admonition
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
